### ISSUE TITLE
Multi-fasta functionality

### ISSUE THREAD

**Issue by matnguyen** [dnbaker/dashing2#79]
Is it in the plans to add multi-fasta functionality, instead of having to have separate fasta files for each sequence?

**Comment by dnbaker** [comment]
You should already be good! All you have to do is put multiple filenames on
the same line for the -F and -Q options. You can also do it for paired-end
reads, for instance.

Would you let me know how that goes?

Thanks,

Daniel

**Comment by matnguyen** [comment]
Hi Daniel, thanks for your reply. 

What I mean by a multi-fasta is a single fasta file that has multiple sequences, a format like this: 

```
>sequenceID-001 description
AAGTAGGAATAATATCTTATCATTATAGATAAAAACCTTCTGAATTTGCTTAGTGTGTAT
ACGACTAGACATATATCAGCTCGCCGATTATTTGGATTATTCCCTG

>sequenceID-002 description
CAGTAAAGAGTGGATGTAAGAACCGTCCGATCTACCAGATGTGATAGAGGTTGCCAGTAC
AAAAATTGCATAATAATTGATTAATCCTTTAATATTGTTTAGAATATATCCGTCAGATAA
TCCTAAAAATAACGATATGATGGCGGAAATCGTC

>sequenceID-003 description
CTTCAATTACCCTGCTGACGCGAGATACCTTATGCATCGAAGGTAAAGCGATGAATTTAT
CCAAGGTTTTAATTTG
```

**Comment by dnbaker** [comment]
Oh great! Just use --parse-by-seq to treat each entry as its own entity.
